services:
  db:
    image: postgres:17.5
    container_name: postgres
    environment:
      POSTGRES_DB: ${DB_NAME:-api}
      POSTGRES_USER: ${DB_USER:-admin}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - ${DB_PORT}:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  redis:
    image: redis:8.0.2-alpine
    container_name: redis
    command: redis-server --requirepass ${REDIS_PASSWORD} --save "" --appendonly no
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    ports:
      - ${REDIS_PORT}:6379
    volumes:
      - redis_data:/data
    restart: always
    
volumes:
  postgres_data:
  redis_data:
