services:
  db:
    image: postgres:17.5
    container_name: postgres
    environment:
      POSTGRES_DB: ${DB_NAME:-api}
      POSTGRES_USER: ${DB_USER:-admin}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - ${DB_PORT}:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

volumes:
  postgres_data: