services:
  api:
    build:
      context: .
      target: production
      dockerfile: Dockerfile
    command: >
      bash -c "
      python manage.py migrate --no-input &&
      exec gunicorn --config gunicorn_conf.py config.asgi:application"
    volumes:
      - ./logs:/app/logs
    deploy:
      replicas: ${REPLICAS:-1}
    networks:
      - backend
    restart: unless-stopped

  nginx:
    image: nginx:1.27.5-alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./logs:/var/log/nginx
    ports:
      - ${PORT:-8000}:80
    depends_on:
      - api
    networks:
      - backend
    restart: unless-stopped

networks:
  backend: